#!/bin/bash
set -ue
# This script is always executed in the **root** of your repository
cd MyConference/
npm install -g gulp
npm install 
chmod +x hooks/after_prepare/010_add_platform_class.js
ionic state reset
cordova platform add android
gulp build
ls platforms/android/
echo
echo "Copying final artifact to docker assets directory"
sudo rm -rf docker/assets/android-debug.apk
sudo mkdir -p docker/assets
ls
sudo cp -v platforms/android/build/outputs/apk/android-debug.apk docker/assets/my-conference.apk
cd docker/assets
ls
